### ISSUE TITLE
model not optimised for new tracks.

### ISSUE THREAD

**Issue by ganesh-lakshman** [Janudis/CarND-Behavioral-Cloning#1]

**Comment by Janudis** [comment]
Hello, what do you mean by new tracks?

**Comment by ganesh-lakshman** [comment]
So the udacity simulator has two tracks right the one that we trained and
the hilly terrain. The model isn't working for hilly terrain.

**Comment by Janudis** [comment]
Understood. I have not tried it for hilly terrain but this could be because the model is trained only on images from the first environment. If you want to make it work for the hilly terrain you should record some images from this environment and train the model again on them.
